<!DOCTYPE html>
<html âš¡ lang="en">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="canonical" href="http://www.yegor256.com" />
    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
    <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
    <script async src="https://cdn.ampproject.org/v0.js"></script>
  </head>
  <body>
    <h1></h1>
    <p>I don&#39;t know whether it&#39;s an anti-pattern or just a common and very popular
mistake, but I see it everywhere and simply must write about it. I&#39;m talking
about <strong>exception catching without
<a href="/2015/12/01/rethrow-exceptions.html">re-throwing</a></strong>. I&#39;m talking about something like
this Java code:</p>

<figure class="highlight"><pre><code class="language-java" data-lang="java"><span class="k">try</span> <span class="o">{</span>
  <span class="n">stream</span><span class="o">.</span><span class="na">write</span><span class="o">(</span><span class="n">data</span><span class="o">);</span>
<span class="o">}</span> <span class="k">catch</span> <span class="o">(</span><span class="n">IOException</span> <span class="n">ex</span><span class="o">)</span> <span class="o">{</span>
  <span class="n">ex</span><span class="o">.</span><span class="na">printStackTrace</span><span class="o">();</span>
<span class="o">}</span></code></pre></figure>

<!--more-->



<p>Pay attention: I don&#39;t have anything against this code:</p>

<figure class="highlight"><pre><code class="language-java" data-lang="java"><span class="k">try</span> <span class="o">{</span>
  <span class="n">stream</span><span class="o">.</span><span class="na">write</span><span class="o">(</span><span class="sc">&#39;X&#39;</span><span class="o">);</span>
<span class="o">}</span> <span class="k">catch</span> <span class="o">(</span><span class="n">IOException</span> <span class="n">ex</span><span class="o">)</span> <span class="o">{</span>
  <span class="k">throw</span> <span class="k">new</span> <span class="nf">IllegalStateException</span><span class="o">(</span><span class="n">ex</span><span class="o">);</span>
<span class="o">}</span></code></pre></figure>

<p>This is called <a href="https://en.wikipedia.org/wiki/Exception_chaining"><em>exception chaining</em></a>
and is a perfectly valid construct.</p>

<p>So what is wrong with catching an exception and logging it? Let&#39;s try to
look at the bigger picture first. We&#39;re talking about object-oriented
programming &mdash; this means we&#39;re dealing with objects. Here is
how an object (its class, to be exact) would look:</p>

<figure class="highlight"><pre><code class="language-java" data-lang="java"><span class="kd">final</span> <span class="kd">class</span> <span class="nc">Wire</span> <span class="o">{</span>
  <span class="kd">private</span> <span class="kd">final</span> <span class="n">OutputStream</span> <span class="n">stream</span><span class="o">;</span>
  <span class="n">Wire</span><span class="o">(</span><span class="kd">final</span> <span class="n">OutputStream</span> <span class="n">stm</span><span class="o">)</span> <span class="o">{</span>
    <span class="k">this</span><span class="o">.</span><span class="na">stream</span> <span class="o">=</span> <span class="n">stm</span><span class="o">;</span>
  <span class="o">}</span>
  <span class="kd">public</span> <span class="kt">void</span> <span class="nf">send</span><span class="o">(</span><span class="kd">final</span> <span class="kt">int</span> <span class="n">data</span><span class="o">)</span> <span class="o">{</span>
    <span class="k">try</span> <span class="o">{</span>
      <span class="k">this</span><span class="o">.</span><span class="na">stream</span><span class="o">.</span><span class="na">write</span><span class="o">(</span><span class="n">x</span><span class="o">);</span>
    <span class="o">}</span> <span class="k">catch</span> <span class="o">(</span><span class="n">IOException</span> <span class="n">ex</span><span class="o">)</span> <span class="o">{</span>
      <span class="n">ex</span><span class="o">.</span><span class="na">printStackTrace</span><span class="o">();</span>
    <span class="o">}</span>
  <span class="o">}</span>
<span class="o">}</span></code></pre></figure>

<p>Here is how I&#39;m using this class:</p>



<p>Looks nice, right? I don&#39;t need to worry about that <code>IOException</code> when I&#39;m
calling <code>send(1)</code>. It will be handled internally, and if it occurs, the stacktrace
will be logged. But this is a totally wrong way of thinking, and it&#39;s inherited
from languages without exceptions, like C.</p>



<p>Exceptions were invented to simplify our design by moving the entire
error handling code away from the main logic. Moreover, we&#39;re not just moving it away but
also concentrating it in one place &mdash; in the <code>main()</code> method, the entry
point of the entire app.</p>

<p>The primary purpose of an exception is to collect as much information as possible
about the error and float it up to the highest level, where the user
is capable of doing something about it. Exception chaining helps even
further by allowing us to extend that information on its way up. We are basically
putting our bubble (the exception) into a bigger bubble every time we
catch it and
<a href="/2015/12/01/rethrow-exceptions.html">re-throw</a>.
When it hits the surface, there are many bubbles, each remaining
inside another like a Russian doll. The original exception is the
smallest bubble.</p>

<p>When you catch an exception without re-throwing it, you basically pop the bubble.
Everything inside it, including the original exception and all other bubbles
with the information inside them, are in your hands.
You don&#39;t let me see them. You use them somehow, but I don&#39;t know how. You&#39;re
doing something behind the scenes, hiding potentially important information.</p>

<p>If you&#39;re hiding that from me, I can&#39;t promise my user that I will be honest
with him and openly report a problem when it occurs. I simply can&#39;t
trust your <code>send()</code> method anymore, and my user will not trust me.</p>

<p>By catching exceptions without re-throwing them, you&#39;re basically breaking the
chain of trust between objects.</p>

<p>My suggestion is to catch exceptions as seldom as possible, and every time
you catch them,
<a href="/2015/12/01/rethrow-exceptions.html">re-throw</a>.</p>

<p>Unfortunately, the design of Java goes against this principle in many places.
For example, Java has checked and un-checked exceptions, while there should only
be checked ones in my opinion (the ones you must catch or declare
as throwable). Also, Java allows multiple exception types to be declared
as throwable in a single method &mdash; yet another mistake; stick to declaring just
one type. Also, there is a generic <code>Exception</code> class at the top of the hierarchy,
which is also wrong in my opinion. Besides that, some built-in classes don&#39;t
allow any checked exceptions to be thrown, like <code>Runnable.run()</code>. There
are many other problems with exceptions in Java.</p>

<p>But try to keep this principle in mind and your code will be cleaner: <code>catch</code> only if you have no other choice.</p>

<p>P.S. Here is how the class should look:</p>

<figure class="highlight"><pre><code class="language-java" data-lang="java"><span class="kd">final</span> <span class="kd">class</span> <span class="nc">Wire</span> <span class="o">{</span>
  <span class="kd">private</span> <span class="kd">final</span> <span class="n">OutputStream</span> <span class="n">stream</span><span class="o">;</span>
  <span class="n">Wire</span><span class="o">(</span><span class="kd">final</span> <span class="n">OutputStream</span> <span class="n">stm</span><span class="o">)</span> <span class="o">{</span>
    <span class="k">this</span><span class="o">.</span><span class="na">stream</span> <span class="o">=</span> <span class="n">stm</span><span class="o">;</span>
  <span class="o">}</span>
  <span class="kd">public</span> <span class="kt">void</span> <span class="nf">send</span><span class="o">(</span><span class="kd">final</span> <span class="kt">int</span> <span class="n">data</span><span class="o">)</span>
    <span class="kd">throws</span> <span class="n">IOException</span> <span class="o">{</span>
    <span class="k">this</span><span class="o">.</span><span class="na">stream</span><span class="o">.</span><span class="na">write</span><span class="o">(</span><span class="n">x</span><span class="o">);</span>
  <span class="o">}</span>
<span class="o">}</span></code></pre></figure>

  </body>
</html>
